language: java

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk11
  - openjdk11

matrix:
  fast_finish: true

sudo: false
install: true

addons:
  apt:
    packages:
      - libc6:i386
      - libx11-6:i386
      - libxext6:i386
      - libxrender1:i386
      - libxi6:i386
      - libxtst6:i386

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent package
  - ./scripts/jet-build.sh


jobs:
  include:
    - stage: codestyle
      jdk: oraclejdk8
      script: mvn com.coveo:fmt-maven-plugin:check


before_deploy:
  - zip -r cli/target/docbleach_linux_amd64.zip cli/target/jet/app/

deploy:
  - provider: script
    script: scripts/publish.sh
    on:
      branch: master
      repo: docbleach/DocBleach
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "qlyOP0Lg06ThcbsEgXW3qaZzS7eMmsZ4XRUVDsYXbnbZFDem46I7fPboZcAAp0g6AX79Kf/NpESfNShGgzoUZlbFkPp5ez/emi48jENv1H7HwDGS6b/rEcUo7V0ktrY3SfCeQhlwOqicMkCqDG8HT1zjK6odlvjSmSFgUcNG2fWsSmQUJkPZW2jzJaO3Ko37sgX/GIo/HgjL7N9Y7P/+/9PPdBV+rGcjLJAgLZgEQVS3OCd2XHPn6AWa0J7ieFn7JzYQXNT6iOfMVnrRsjsMuTLQKbclFgJb8SZfzJdrOaLY259JumSmGe5Y7SsuN2bRRmFt3H6yF46qptjlPz7ozJCuE4DozVowCjoY+U5ecvx6oMg5WFsFbAipaMWIe6LlZCajqN6RGgPeYwZlfIBbHmj3KGwXOrd3HCslL+D4ZDv/+9QfRriESgaJSSwI/IkT2thHDY+D7FTyRCmKY6S3jcxNGaFz4WRJeFTKMMq1vI0+wI41mRbOg7n5kaNdbCO4vXpBNC/Zhnv0DOD8Zhy/LyGnm9hlfJ10+SF6bxmdKdln9i49AdyaHzVDZCR1/X1lM6mfk1lryzj0jsYVNmYN7JhcsLiUGSY0zSrtSCMQmvajjuPPMFqWXFTj/Kz6aCCIlbsZQAHTntnQr21VMaWqa8JUJ3E6vJYZf1ZtKIy0mpk="
    file:
      - cli/target/docbleach.jar
      - cli/target/docbleach_linux_amd64.zip
    on:
      repo: docbleach/DocBleach
      tags: true